- platform: darksky
  api_key: !secret dark_sky_key
  language: it
  monitored_conditions:
    - summary
    - temperature
    - apparent_temperature
    - temperature_high
    - temperature_low
    - humidity
    - precip_type
    - precip_intensity
    - precip_probability
- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: network_in
      arg: 'wlan0'
    - type: network_out
      arg: 'wlan0'
    - type: processor_use

- platform: "mqtt"
  name: "MijiaSwitchOne"
  state_topic: "zigbee2mqtt/0x00158d0001e824c9"
  availability_topic: "zigbee2mqtt/bridge/state"
  icon: "mdi:toggle-switch"
  value_template: "{{ value_json.click }}"
  json_attributes: 
    - "battery"
    - "voltage"
    - "action"
    - "duration"
  force_update: true